---

- set_fact:
    kibana_addr: "{{ kibana_server_host }}"
    kibana_port: "{{ kibana_server_port }}"

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Kibana.
  package: name="kibana={{ kibana_version_apt }}" state=present

#Module kibana_plugin do not works as it use "kibana plugin --install" instead of "kibana-plugin install"
- name: Test if kibana plugin "X-pack" is present
  become: yes
  shell: "./kibana-plugin list | grep 'x-pack'"
  args:
    chdir: "/usr/share/kibana/bin/"
  register: kibana_xpack_installed
  # grep will exit with 1 when no results found.
  # This causes the task not to halt play.
  ignore_errors: true

- name: Add X-Pack plugin to kibana
  become: yes
  command: "./kibana-plugin install x-pack"
  args:
    chdir: "/usr/share/kibana/bin/"
  when: kibana_xpack_installed|failed

- name: Ensure Kibana is started and enabled at boot.
  service:
    name: kibana
    state: started
    enabled: yes

- name: Copy Kibana configuration.
  template:
    src: kibana.yml.j2
    dest: "/etc/kibana/kibana.yml"
    owner: root
    group: root
    mode: 0644
  notify: restart kibana
